# Generated by Django 5.2.7 on 2025-11-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesRecord',
            new_name='SalesData',
        ),
    ]
